### ISSUE TITLE
npm install issue after updates in package.json

### ISSUE THREAD

**Issue by bmbrands** [bmbrands/moodle-theme_reboost#10]
After the package.json file has been updated I am getting some errors:

18851 verbose stack Error: node-sass@4.7.2 postinstall: `node scripts/build.js`
18851 verbose stack Exit status 1
18851 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
18851 verbose stack     at emitTwo (events.js:126:13)
18851 verbose stack     at EventEmitter.emit (events.js:214:7)
18851 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18851 verbose stack     at emitTwo (events.js:126:13)
18851 verbose stack     at ChildProcess.emit (events.js:214:7)
18851 verbose stack     at maybeClose (internal/child_process.js:925:16)
18851 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
18852 verbose pkgid node-sass@4.7.2
18853 verbose cwd /Users/basbrands/Documents/www/moodle/theme/reboost
18854 verbose Darwin 17.4.0
18855 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
18856 verbose node v8.9.4
18857 verbose npm  v5.6.0
18858 error code ELIFECYCLE
18859 error errno 1
18860 error node-sass@4.7.2 postinstall: `node scripts/build.js`
18860 error Exit status 1
18861 error Failed at the node-sass@4.7.2 postinstall script.
18861 error This is probably not a problem with npm. There is likely additional logging output above.
18862 verbose exit [ 1, true ]

**Comment by jobyh** [comment]
Hi @bmbrands are you still encountering this issue?

**Comment by bmbrands** [comment]
Ah no... you fixed that :)
